### ISSUE TITLE
alexapy and config_flow error 4.12.5 (Running 2024.8.0b8)

### ISSUE THREAD

**Issue by KyleStilkey** [alandtse/alexa_media_player#2412]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When adding the integration and setting up, I am now presented with Alexapy and Authenitcation isssues (I'm sure due to not being able to call the apis and unsure if it's related to AMP or AlexaPy.

**To Reproduce**

Install AMPS, login with details and this error occurs.

**Expected behavior**

It should work and pull all Alexa devices

**Screenshots**

**System details**

- Home-assistant (version): 2024.8.0b8
- alexa_media (version from `const.py` or HA startup): 4.12.5
- alexapy (version from `pip show alexapy` or HA startup): 1.28.1
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**

```
Alexa Media Reauthentication Required
Reauthenticate [removed](mailto:removed) on the [Integrations](removed url) page. Relogin required after 0:00:00.226034 and 1 api calls.
```

```
Logger: alexapy.helpers
Source: runner.py:190
First occurred: 11:29:39 AM (7 occurrences)
Last logged: 11:29:39 AM

alexaapi.get_authentication((<alexapy.alexalogin.AlexaLogin object at 0x7fb391c7d970>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x7fb391c7d970>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
alexaapi.get_dnd_state((<alexapy.alexalogin.AlexaLogin object at 0x7fb391c7d970>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
alexaapi.get_bluetooth((<alexapy.alexalogin.AlexaLogin object at 0x7fb391c7d970>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
alexaapi.get_device_preferences((<alexapy.alexalogin.AlexaLogin object at 0x7fb391c7d970>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/alexa_media/config_flow.py:815
integration: Alexa Media Player (documentation, issues)
First occurred: 11:29:39 AM (1 occurrences)
Last logged: 11:29:39 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 251, in relogin
    if await test_login_status(hass, config_entry, login_obj):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1421, in test_login_status
    ] = await hass.config_entries.flow.async_init(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1293, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1323, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 578, in async_step_reauth
    reauth_schema = self._update_schema_defaults()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 815, in _update_schema_defaults
    CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, hass_url)
                                                          ^^^^^^^^
NameError: name 'hass_url' is not defined
```

**Additional context**

When going to terminal and calling for the pip show alexapy I got no package found, so I installed it with install alexapy and have version 1.28.1

I have tried fully removing AMP and restarting each uninstall and install step to make sure nothing is left behind but it always results back to these two errors.

**Comment by dthomas946** [comment]
I uninstalled the Integration, then reinstalled it and was able to re-authenticate.  Seems to be working again

**Comment by KyleStilkey** [comment]
> I uninstalled the Integration, then reinstalled it and was able to re-authenticate. Seems to be working again

Yeah I tried that, still get the same errors thrown at me.

**Comment by chrisvblemos** [comment]
Known issue, #2409

**Comment by bkr1969** [comment]
No luck uninstalling and re-installing.  The integration "installs" but none of my devices are listed.  If I reconfigure I just get errors:

```

Logger: alexapy.helpers
Source: runner.py:190
First occurred: 15:16:41 (6 occurrences)
Last logged: 15:16:41

alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0xffff3bfcfa10>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Unauthorized',)
alexaapi.get_authentication((<alexapy.alexalogin.AlexaLogin object at 0xffff3bfcfa10>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
alexaapi.get_dnd_state((<alexapy.alexalogin.AlexaLogin object at 0xffff3bfcfa10>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
alexaapi.get_bluetooth((<alexapy.alexalogin.AlexaLogin object at 0xffff3bfcfa10>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
alexaapi.get_device_preferences((<alexapy.alexalogin.AlexaLogin object at 0xffff3bfcfa10>,), {}): An error occurred accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()
```
And:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/alexa_media/config_flow.py:815
integration: Alexa Media Player (documentation, issues)
First occurred: 15:16:41 (1 occurrences)
Last logged: 15:16:41

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 251, in relogin
    if await test_login_status(hass, config_entry, login_obj):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1421, in test_login_status
    ] = await hass.config_entries.flow.async_init(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1293, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1323, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 578, in async_step_reauth
    reauth_schema = self._update_schema_defaults()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 815, in _update_schema_defaults
    CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, hass_url)
                                                          ^^^^^^^^
NameError: name 'hass_url' is not defined
```

**Comment by ziolelle** [comment]
Same here with core 2024.8.0 and Alexa Media Player 4.12.5

**Comment by danielbrunt57** [comment]
This is fixed in AMP v4.12.6 just released.

**Comment by Stephan-4711** [comment]
I just updated to 4.12.6 but still the same erro.
`Logger: homeassistant.config_entries
Quelle: config_entries.py:604
Erstmals aufgetreten: 08:19:41 (1 Vorkommnisse)
Zuletzt protokolliert: 08:19:41

Error setting up entry my@email.de - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 359, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 687, in login
    post_resp = await self._session.post(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 576, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: /errors/validateCaptcha`

**Comment by nwootton** [comment]
+1 to that

**Comment by mistergyle** [comment]
manual fix can be found here: https://github.com/alandtse/alexa_media_player/issues/2418#issuecomment-2274998884

**Comment by Stephan-4711** [comment]
@mistergyle @danielbrunt57 wrote it's fixed in 4.12.6

**Comment by mistergyle** [comment]
> @mistergyle @danielbrunt57 wrote it's fixed in 4.12.6

wasn't for me:( after i applied the above mentioned fix it is working again now.

**Comment by bkr1969** [comment]
Why was this issue closed?  The integration IS NOT working.

**Comment by bkr1969** [comment]
> > @mistergyle @danielbrunt57 wrote it's fixed in 4.12.6
> 
> wasn't for me:( after i applied the above mentioned fix it is working again now.

Can you please describe exactly the steps you took to fix??

**Comment by KyleStilkey** [comment]
It's been fixed, 4.12.7 was pushed to update Alexapy to the latest version that fixes the issue. The fix posted was people editing the line to make it pull the update ahead of the fix push.

Give 4.12.7 a try and if still problems, open up a new bug report with your logs and details so they can help.

**Comment by petrotti77** [comment]
Dopo l'aggiornamento 4.12.7 il problema è stato risolto parzialmente per me. Riesco ad auteticarmi ma le automazioni che integrano le notifiche tramite echo non funzionano e continuano a persistere problemi di riatenticazione giornaliere. Attualmente l'integrazione alexa media player è fuori uso per me. Sarà possibile tornare ad utilizzare l'itegrazione come prima della versione 2024.8? Se ci sono altri suggerimenti da parte vostra non esiterò a provarli. Grazie.
