### ISSUE TITLE
alexa_media_everywhere no longer sends message to every Alexa device (specifically a echo show 8 is excluded for some reason)

### ISSUE THREAD

**Issue by pcmike** [alandtse/alexa_media_player#2744]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After the most recent spat of updates (I'm ~~not~~ now on 5.0.4) my automations using notify.alexa_media_everywhere no longer play a message on every echo device; specifically the echo show 8 in the kitchen does not play the message.

**To Reproduce**

Try sending a message to notify.alexa_media_everywhere

**Expected behavior**

Every echo speaker should be outputting the same message

**System details**

- Home Assistant version: HAOS 2024.12.2
- alexa_media version (from `const.py` or HA startup log): 5.0.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): no clue how to get into the container
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: no clue? I'm US based

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by sayam93** [comment]
Did you face this issue with 5.0.2? If not and 5.0.3 broke it, 5.0.4 should fix it.

> **IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**
> 
> **Describe the bug**
> 
> After the most recent spat of updates (I'm not on 5.0.4) my automations using notify.alexa_media_everywhere no longer play a message on every echo device; specifically the echo show 8 in the kitchen does not play the message.
> 
> **To Reproduce**
> 
> Try sending a message to notify.alexa_media_everywhere
> 
> **Expected behavior**
> 
> Every echo speaker should be outputting the same message
> 
> **System details**
> 
> * Home Assistant version: HAOS 2024.12.2
> * alexa_media version (from `const.py` or HA startup log): 5.0.4
> * alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): no clue how to get into the container
> * Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
> * Amazon Domain: no clue? I'm US based
> 
> **Debug Logs (alexa_media & alexapy)** Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
> 
> **Additional context**

**Comment by pcmike** [comment]
I’m sorry, I got autocorrected as I was rushing out of the house. The not should be a now. I am on 5.0.4 and the issue still exists.

**Comment by sayam93** [comment]
> I’m sorry, I got autocorrected as I was rushing out of the house. The not should be a now. I am on 5.0.4 and the issue still exists.

Was this present in 5.0.2? 5.0.4 reverts the changes made in 5.0.3 and only changes the text for error message.

**Comment by pcmike** [comment]
Unsure, I believe so.

**Comment by sayam93** [comment]
> Unsure, I believe so.

Could you possibly rollback and double check?

**Comment by sayam93** [comment]
> Unsure, I believe so.

https://github.com/alandtse/alexa_media_player/compare/v5.0.2...v5.0.4

The only changes between 5.0.2 and 5.0.4 besides version number is that error messages have been added to const.py and are being imported from there. This simply replaces:

"To send TTS, please set Announce=true. Music can't be played this way."

with

"Sorry, direct music streaming isn't supported. This limitation is set by Amazon, and not by Alexa-Media-Player, Music-Assistant, nor Home-Assistant."

That shouldn't break the functionality you have mentioned unless it was already broken in 5.0.2

**Comment by danielecolantonio** [comment]
Has anyone managed to find a solution?

**Comment by danielbrunt57** [comment]
> notify.alexa_media_everywhere no longer play a message on every echo device; specifically the echo show 8 in the kitchen does not play the message.

Does your Everywhere audio group in Alexa include the Echo Show 8?
Mine did not but I added it to test your situation and `notify.alexa_media_everywhere` now plays the message on all the devices I have in that audio group, including my Echo Show 8.
![Screenshot_20250106_211502_Amazon Alexa](https://github.com/user-attachments/assets/c1da799c-c106-489b-af50-3ef9136919ac)
![Screenshot_20250106_211556_Amazon Alexa](https://github.com/user-attachments/assets/c4c0bb5f-8887-4dac-93a2-95812e5f27d9)
