### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by Evil-Teddy** [alandtse/alexa_media_player#2844]
Same behaviour like in this closed issue:
https://github.com/alandtse/alexa_media_player/issues/2702

**Describe the bug**

Some days ago all my devices in the alexa media player integration were shown but not available anymore so they had no funktion nor were controllable.
After reinstall the integration from ground up, the setup is working but now no devices were found.

**To Reproduce**

1. Configure Alexa Media Player 
2. Observe that no devices are found

**Expected behavior**

Devices should be discoverable and controllable 

**Screenshots**

![Image](https://github.com/user-attachments/assets/c7d918e7-d970-455d-a687-0fefb965bb1e)

![Image](https://github.com/user-attachments/assets/e337b4f7-57c8-400e-82da-13cb11ba2c7a)

**System details**

- Home Assistant version:
  - Core = 2025.2.5
  - Supervisor = 2025.03.0
  - Operating System = 14.2
- alexa_media version (from `const.py` or HA startup log): 5.5.1
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.5
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account): yes
- Amazon Domain: amazon.de

**Debug Logs (alexa_media & alexapy)**

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.alexa_media
Quelle: helpers/update_coordinator.py:412
Integration: Alexa Media Player (Dokumentation, Probleme)
Erstmals aufgetreten: 14:03:20 (1 Vorkommnisse)
Zuletzt protokolliert: 14:03:20

Error fetching alexa_media data: Error communicating with API: 'AAA_SonarCloudService_64e8b053-fc77-3673-a837-cdfb3eabc983'

[home-assistant_2025-03-04T13-08-11.702Z.log](https://github.com/user-attachments/files/19071514/home-assistant_2025-03-04T13-08-11.702Z.log)

**Comment by Evil-Teddy** [comment]
I see that we have an other issue with the same problem and at the end someone wrotees that he solved the problem with sowngrading to version 5.3.0 (https://github.com/alandtse/alexa_media_player/issues/2817#issuecomment-2684470314), but I hope thats an workaround, because I would like to use the newest version.

I tried it with version 5.3.0 and that worked for me too.

**Comment by giovanni247000** [comment]
I also have the same problem, I enter all the data as I did before, the integration is added successfully without multiple devices, is there any news???

**Comment by GitHubStephan** [comment]
same problem for me. i tried to install 5.3 and earlier versions but does not help. when i use amazon.com i can see the devices but they are unavailable. with amazon.de there are no devices. i checked my amazon account and its pretty clear that my account and devices are under amazon.de

**Comment by Supermario3012** [comment]
Same problem here. Did several new configurations of AMP and tried to downgrade to 5.3.0. Up to now nothing helped.
Always get this error:
Logger: custom_components.alexa_media
Quelle: helpers/update_coordinator.py:412
Integration: Alexa Media Player (Dokumentation, Probleme)
Erstmals aufgetreten: 16:25:39 (2 Vorkommnisse)
Zuletzt protokolliert: 19:03:36

Error fetching alexa_media data: Error communicating with API: 'NoneType' object is not subscriptable

**Comment by Supermario3012** [comment]
Just spoke to Amazon hotline for a while. They a sure that the problem lies with the HA AMP integration! I am of the same opinion. The solution can not be to always crate a new account with Amazon. 
The problem has to be looked into in more detail on the integration side.
I would offer to assist as much as I can.

**Comment by Genius311273** [comment]
I don't remember my exact issues with this. But After Upgradin from Version 5.3.0 I had similar issues... no devices found... 
No Echo devices.. but the Fire TV devices were ok.
I then started to delete the echo devices one by one from my Amazon Account via https://www.amazon.de/hz/mycd/digital-console/alldevices?pageType=devices&ref_=ya_d_l_manage_devices
Then readded one by one to the current amazon account again... (Don't know if I delete the AMP integration completely, but give it a try!)
Since then, no issues with Version 5.6.0

**Comment by danielbrunt57** [comment]
> Just spoke to Amazon hotline for a while. They a sure that the problem lies with the HA AMP integration!

I've contacted them a few times over the years and always found their support to be almost as "useless as tits on a bull"!

> The solution can not be to always crate a new account with Amazon.

I never said that!  I said "try this" and YMMV.

**Comment by Supermario3012** [comment]
Created a new account and moved Echo devices. Yes, devices found and AMP worked again. Up to last Sunday everything worked with 5.6.0 for weeks. Only then something changed, that made Echo devices unavailable.
I also deleted the AMP integration, downgraded to 5.3.0 but nothing helped. However it is worse now. Until Sunday only the Echo devices reported unavailable, but were alt least reported with all other devices. Since the new installation no device is found anymore.

I tried the @Genius311273 method, but it does not seam to work in my case.

I noticed also a difference between the old and the new account. In the new account authentification APPs can be added and deleted.
The delete option is missing on the old account. Due to several trials, there are 12 APPs reported that cannot be deleted.
I made Amazon aware of this difference and asked them to delete all authentification APPs. Currently they are looking into it and will come back to me.

**Comment by Evil-Teddy** [comment]
I was considering doing the steps with a new Amazon account, but after what @Supermario3012 wrote here, I'd rather leave it for now, since it made the situation much worse for him. I'm still on AMP version 5.3.0 and at least it's working. As soon as I update, it stops working, and if I switch to a new Amazon account, it seems it doesn't work either — not even when downgrading back to 5.3.0.

**Comment by danielbrunt57** [comment]
I don't have an answer except stick with your old account and 5.3.0...

**Comment by Supermario3012** [comment]
Should be solved now with 5.7.0. My Integration is working again.

**Comment by Evil-Teddy** [comment]
I can confirm that the devices are shown again with version 5.7.0. But now my automations aren't working anymore because homeassistant didn't find notify.alexa_media anymore.

**Comment by Evil-Teddy** [comment]
I checked everything again and with version 5.7.0 I still have the issue that the devices aren't availeble anymore and doesn't finde the notify.alexa_media service. So I had to go back to 5.3.0 and everything is working fine.

**Comment by AprilWexler** [comment]
### tl;dr:
I tried AMP 5.3 and 5.7.2 - both are not working for me with amazon.**de**

I raised the same issue in the forum: https://community.home-assistant.io/t/alexa-media-player-doesnt-show-up-although-integration-was-installed-successful/885926

### long version:
I successful installed Alexa Media Player Integration via HACS. Login to [amazon.de](http://amazon.de/) was ok, 2FA as well - all good, but Alexa Media Players do not show up in HA. It says: no devices, no entities (but I do have 5 echo devices).

I tried the same process using amazon.com (instead of amazon.de) and all echo devices were shown immediately and were added. But I cannot use the entities because they are flagged as “unavailable” due to wrong amazon-domain.

If more information is needed please let me know.
I tried using HA in a VM on Synology and HA in a Parallels-VM (MacOS).

**Comment by joaoarthur** [comment]
i have the same issue. 
First my echos seems as unavailable at AMP 5.3.0 version. 
So i updated to the AMP 5.7.3 version and then, all my devices are gone.

Some one could  solve this?

**Comment by Evil-Teddy** [comment]
hey it's me again. The last months I used version 5.3.0 of AMP and with that version everything worked as expected. But of course that was only a workaround for me. But now with the newest HA update, the 5.3.0. doesn't work anymore to. Same behavior and same issues with the newer versions. No devices and no notify.

**Comment by joaoarthur** [comment]
same with me.
the AMP died?

**Comment by NordFreak** [comment]
my version via hacs:

<img width="230" height="109" alt="Image" src="https://github.com/user-attachments/assets/627695c2-c8ef-401e-8aad-3942485080bd" />

It is true that not all functions currently work:

<img width="353" height="780" alt="Image" src="https://github.com/user-attachments/assets/a5e1980b-7ebf-49f1-91d2-3bd3b5b8dbac" />

But in my use case, I can say that everything I need works: voice output and accepting commands. Even controlling the volume.

What no longer works, for example, is that I can say “pause” to my Echo and the playback on the FireTV stops.

**Comment by joaoarthur** [comment]
I solve the problem in my case. I did a few things and i will describe here, because i cant precise wich really solve to me.

1) the old version of AMP was in my archive structure and in the log i saw that e HA was trying to use the old one. 
  So i fiscally remove the old version.
2) I change my amazon 2FA from SMS to App microsoft app using this tutorial to add de amazon at microsoft authenticator.

<img width="1050" height="639" alt="Image" src="https://github.com/user-attachments/assets/a6132cef-5023-4b7f-bc79-91ad01470106" />

3) Installing 5.7.3 AMP Version an the last HA version.

4) restart HA

**Comment by crsmoro** [comment]
same issue here.. tried all the sugested solutions nothing works for me..
is there an update on this?

**Comment by joaoarthur** [comment]
> same issue here.. tried all the sugested solutions nothing works for me.. is there an update on this?

go to your logs and search for any errors in AMP.  It's the best clue that you will get to give the next setp..

**Comment by Evil-Teddy** [comment]
Still no Solution? Tried new Version nur Theo it is the same issue.

5.7.3 is working for ne so far but I would like to sie the newer versions too

**Comment by danielbrunt57** [comment]
Are your devices registered in amazon.de or amazon.com??

**Comment by Evil-Teddy** [comment]
They are registered at amazon.de

**Comment by ecoen66** [comment]
Same issue.  Fresh install on new HA instance.

**Comment by sergey08** [comment]
Same issue, amazon.es

**Comment by lordraw77** [comment]
same issue, amazon.it 

Installation method
Home Assistant OS
Core
2025.10.2
Supervisor
2025.10.0
Operating System
16.2
Frontend
20251001.2

Alexa media player v5.7.8

**Comment by PowLee88** [comment]
same issue here!

**Comment by milkog** [comment]
Same issue here. Alexa media player v5.7.8, Core 2025.10.3

**Comment by lordraw77** [comment]
After update to Version Alexa media player 5.7.9

Home Assistant OS
Core
2025.10.2
Supervisor
2025.10.0
Operating System
16.2
Frontend
20251001.2

continue no work 


Logger: homeassistant.components.alexa_devices
Source: helpers/update_coordinator.py:424
integration: Alexa Devices (documentation, issues)
First occurred: 2:19:07 PM (28 occurrences)
Last logged: 3:17:07 PM

Error fetching  xxx@gmail.com data: Error retrieving data: CannotRetrieveData('Request failed: Bad Request')

**Comment by danielbrunt57** [comment]
Closing this as a stale issue for `Error fetching alexa_media data: Error communicating with API: 'AAA_SonarCloudService_64e8b053-fc77-3673-a837-cdfb3eabc983'`.  if you are having issues other the subject of this one, please refer to newer issues that are more relevant to your scenario.
