### ISSUE TITLE
Temperature sensors sometimes unavailable

### ISSUE THREAD

**Issue by omlnaut** [alandtse/alexa_media_player#3134]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The bug described in #3129 occurs periodically for me. The temperature sensor is available for some time, then unavailable, then back. This seems to switch back and forth.

**To Reproduce**

1. Go to history of temperature sensor, see gaps.

**Expected behavior**

Sensor should be available all the time.

**Screenshots**

<img width="1080" height="915" alt="Image" src="https://github.com/user-attachments/assets/578731ad-44fd-4245-9116-ca95ad6a6219" />

**System details**

- Home Assistant version: 2025.11.2
- alexa_media version (from `const.py` or HA startup log): 5.7.13
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2SV via Authenticator App](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (not 2SV OTP via SMS) enabled?  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
This error originated from a custom integration.

Logger: custom_components.alexa_media
Source: helpers/update_coordinator.py:435
integration: Alexa Media Player (documentation, issues)
First occurred: 09:18:22 (1 occurrence)
Last logged: 09:18:22

Error fetching alexa_media data: Error communicating with API: object of type 'NoneType' has no len()

Adding debug logs as attachment.

[latest.txt](https://github.com/user-attachments/files/23577499/latest.txt)

**Additional context**

**Comment by R1200G** [comment]
I have the same problem since this early morning 01:45h...

<img width="833" height="720" alt="Image" src="https://github.com/user-attachments/assets/781331e8-09a8-4b6e-9655-c4f87a77098a" />

**Comment by omlnaut** [comment]
> I have the same problem since this early morning 01:45h...
> 
> <img alt="Image" width="833" height="720" src="https://private-user-images.githubusercontent.com/118360432/515047518-781331e8-09a8-4b6e-9655-c4f87a77098a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzNjc0OTQsIm5iZiI6MTc2MzM2NzE5NCwicGF0aCI6Ii8xMTgzNjA0MzIvNTE1MDQ3NTE4LTc4MTMzMWU4LTA5YTgtNGI2ZS05NjU1LWM0Zjg3YTc3MDk4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QwODEzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjFhMGEzZDU1NTdjZWFkYjhjOWI0ZWFlMjAxMDZhNmZjZDFkODFiODdmNDZlMTc1NGIyZTE0ZjAwNmFhZDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KaVGiIpiM4uvZ7GK_yL-oJjDCUxC3uFWqwloOvjqnOA">

For me it started this morning 1:20am, so about the same time

**Comment by TeddyPatard** [comment]
Just after the last update for me. I will be rollback

**Comment by buds** [comment]
Same here since 0:25 UTC but I'm still on Version 5.7.11
Reloading the intergration brought it back while it was showing as unavailable.
Possibly an Amazon issue?

**Comment by omlnaut** [comment]
> Same here since 0:25 UTC but I'm still on Version 5.7.11 Reloading the intergration brought it back while it was showing as unavailable. Possibly an Amazon issue?

Restarting Homeassistent was one of the first things I tried ;)

Right now the temperature sensors seem to be stable since 10am, so 1h20m. Definitely much longer than they were before.

Edit: Nevermind, they just became unavailable again :(

**Comment by blue-bean** [comment]
I think also it's an Amazon issue.

**Comment by danielbrunt57** [comment]
Most likely a polling failure due to GraphQL responding "Too many requests".

**Comment by omlnaut** [comment]
I increased the polling interval from 60s to 300s, that didn't help either :/

**Comment by omlnaut** [comment]
It looks like fetching notifications via amazon api is the problem. I found this in my debug logs:

<img width="1136" height="106" alt="Image" src="https://github.com/user-attachments/assets/4d61e4a2-770a-4df4-bdb2-9293ed5c1289" />

which probably comes from this call in alexapy:

<img width="661" height="381" alt="Image" src="https://github.com/user-attachments/assets/53abaa26-2e15-4a21-b80c-535a9cb33d24" />

which is used like this in AMP:

<img width="702" height="481" alt="Image" src="https://github.com/user-attachments/assets/33c95511-00ba-4c75-991d-ff31e5f5106f" />

I added fancy highlighting for the problematic code parts. Notifications are fetched, some stuff is done when they are not None... but then we call len(raw_notifications) anyway. Not even for something important, it's just the debug log :/

At the end this method is used here:

<img width="673" height="295" alt="Image" src="https://github.com/user-attachments/assets/8968701f-a7c2-409e-a267-fa7f91b1bf61" />

, throws the len(None) exception and triggers the error log that I see in homeassistant logs.



It might be worth just fixing the None handling here. I don't really know how to contribute to this repo though, so any pointers are welcome.

> Most likely a polling failure due to GraphQL responding "Too many requests".

Worth mentioning: It does not seem to be "TooManyRequests", as that would've triggered a different error in alexapy:

<img width="620" height="450" alt="Image" src="https://github.com/user-attachments/assets/f9acc490-275d-4ef5-9938-6518af9cc886" />

**Comment by danielbrunt57** [comment]
> It looks like fetching notifications via amazon api is the problem. I found this in my debug logs:
> 
> <img alt="Image" width="1136" height="106" src="https://private-user-images.githubusercontent.com/38887646/515376146-4d61e4a2-770a-4df4-bdb2-9293ed5c1289.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MjMzMTMsIm5iZiI6MTc2MzQyMzAxMywicGF0aCI6Ii8zODg4NzY0Ni81MTUzNzYxNDYtNGQ2MWU0YTItNzcwYS00ZGY0LWJkYjItOTI5M2VkNWMxMjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE3VDIzNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NTA2NGFmODg3YjE4YWQzZTkxN2M1ZjAyNDU2OTE4MzJlNGE2ZWU0ZGU1OGJhNTFjZWQxMjA3MjVkMjVjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OToYNaUef0phjBx34IZE4zWuuEL8mqe0ZmsX2ZlAWn0">
> which probably comes from this call in alexapy:
> 
> <img alt="Image" width="661" height="381" src="https://private-user-images.githubusercontent.com/38887646/515376372-53abaa26-2e15-4a21-b80c-535a9cb33d24.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MjMzMTMsIm5iZiI6MTc2MzQyMzAxMywicGF0aCI6Ii8zODg4NzY0Ni81MTUzNzYzNzItNTNhYmFhMjYtMmUxNS00YTIxLWI4MGMtNTM1YTljYjMzZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE3VDIzNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlM2ZjMWY0ODBhNWEyNTIxNGI3ZWY1NTYyZTE2YWVjYTg0MDMyYmQ3NjcxYTBkMjM0M2FkZjkzMmU4NGU2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hL6JQYSP4_ou89vMG8uANmgY6fLzjsNlFbBzZfeQ9Tg">
> which is used like this in AMP:
> 
> <img alt="Image" width="702" height="481" src="https://private-user-images.githubusercontent.com/38887646/515376851-33c95511-00ba-4c75-991d-ff31e5f5106f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MjMzMTMsIm5iZiI6MTc2MzQyMzAxMywicGF0aCI6Ii8zODg4NzY0Ni81MTUzNzY4NTEtMzNjOTU1MTEtMDBiYS00Yzc1LTk5MWQtZmYzMWU1ZjUxMDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE3VDIzNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzODliNmViNjU0OWRjYjJkNTI1MDJiYWY3MzI5NzQyNGMxOTA3MDU4ZjZiNjI3MWM1NDc4OTRjOGNkNDFjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sscdAOwrkqmRUvG0Gf7rAdPHDSdfK-zNc7-1xzhTVww">
> I added fancy highlighting for the problematic code parts. Notifications are fetched, some stuff is done when they are not None... but then we call len(raw_notifications) anyway. Not even for something important, it's just the debug log :/
> 
> At the end this method is used here:
> 
> <img alt="Image" width="673" height="295" src="https://private-user-images.githubusercontent.com/38887646/515377583-8968701f-a7c2-409e-a267-fa7f91b1bf61.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MjMzMTMsIm5iZiI6MTc2MzQyMzAxMywicGF0aCI6Ii8zODg4NzY0Ni81MTUzNzc1ODMtODk2ODcwMWYtYTdjMi00MDllLWEyNjctZmE3ZjkxYjFiZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE3VDIzNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ODFkMmQwMGI0Yzc3NmQ1M2Q5YmUwNGI1NmQzYmE4NGVlZDA1YjdhNWZhMjUzOTE1ZjhiNWVkMDM4N2UwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7fy6BAA_VtO3bjxszTN_stce2S_JLXThHjthe9gXWks">
> , throws the len(None) exception and triggers the error log that I see in homeassistant logs.
> 
> It might be worth just fixing the None handling here. I don't really know how to contribute to this repo though, so any pointers are welcome.
> 
> > Most likely a polling failure due to GraphQL responding "Too many requests".
> 
> Worth mentioning: It does not seem to be "TooManyRequests", as that would've triggered a different error in alexapy:
> 
> <img alt="Image" width="620" height="450" src="https://private-user-images.githubusercontent.com/38887646/515379215-f9acc490-275d-4ef5-9938-6518af9cc886.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MjMzMTMsIm5iZiI6MTc2MzQyMzAxMywicGF0aCI6Ii8zODg4NzY0Ni81MTUzNzkyMTUtZjlhY2M0OTAtMjc1ZC00ZWY1LTk5MzgtNjUxOGFmOWNjODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE3VDIzNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZTFmOGM0Y2M5ZGViMmJhYmVlNDIxYmRmODRhYTdlNjc2ZDRlMjgwMjBiZmFlNGQyMmVjYjk4ZmNiODMyOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VfihoyWUHVZ1wwOohFpaB5OorjkmPvGglPpfPib14xk">

After analyzing the code above, the 400 "Bad Request" is returning no notifications and I think that logger command should be adjusted to:
```
        _LOGGER.debug(
            "%s: Updated %s notifications for %s devices at %s",
            hide_email(email),
            len(raw_notifications) if raw_notifications else 0,
            len(notifications),
            dt.as_local(
                hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"][
                    "process_timestamp"
                ]
            ),
        )
```

Can you edit the `len(raw_notifications,` in your code?
It may then fail on the next len() in which case, that should probably be `len(notifications) if notifications else 0,`

**Comment by danielbrunt57** [comment]
> After analyzing the code above, the 400 "Bad Request" is returning no notifications and I think that logger command should be adjusted to:
> 
> ```
>         _LOGGER.debug(
>             "%s: Updated %s notifications for %s devices at %s",
>             hide_email(email),
>             len(raw_notifications) if raw_notifications else 0,
>             len(notifications),
>             dt.as_local(
>                 hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"][
>                     "process_timestamp"
>                 ]
>             ),
>         )
> ```
> 
> Can you edit the `len(raw_notifications,` in your code? It may then fail on the next len() in which case, that should probably be `len(notifications) if notifications else 0,`

Or perhaps:
```
                if n_dev_id not in notifications:
                    notifications[n_dev_id] = {}
                if n_type not in notifications[n_dev_id]:
                    notifications[n_dev_id][n_type] = {}
                notifications[n_dev_id][n_type][n_id] = notification
                _LOGGER.debug(
                    "%s: Updated %s notifications for %s devices at %s",
                    hide_email(email),
                    len(raw_notifications),
                    len(notifications),
                    dt.as_local(
                        hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"][
                            "process_timestamp"
                        ]
                    ),
                )
            else:
                _LOGGER.debug(
                    "%s: No notifications were retrieved at %s",
                    hide_email(email),
                    dt.as_local(
                        hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"][
                            "process_timestamp"
                        ]
                    ),
                )
        hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"] = notifications

**Comment by omlnaut** [comment]
> "%s: Updated %s notifications for %s devices at %s",

I changed the code on in custom_components/alexa_media_player/__init__.py and reloaded the component. My changes don't seem to be active though. I added bunch of log statements to see where the error occurs, but I get none of those in the debug log.
I changed the file with the File Editor plugin and saved, then reloaded the AMP extension. Is there something else I have to do so that changes to those local files are picked up?

Edit:
Rebooting HA seems to do the trick. So far the suggested code change seems to work the temperature sensors have not gone unavailable for over an hour. I'll try creating a PR this evening, though can't promise I'll find the time.

**Comment by omlnaut** [comment]
Welp. After 2 hours of trying to figure out why my ssh keys stopped working I found that github is having an incident right now. So no PR today, sorry :/

<img width="1052" height="615" alt="Image" src="https://github.com/user-attachments/assets/78600467-59ec-4cf3-b1ab-e1803d20e5c1" />

**Comment by TJWhiteStar** [comment]
>                 if n_dev_id not in notifications:
>                     notifications[n_dev_id] = {}
>                 if n_type not in notifications[n_dev_id]:
>                     notifications[n_dev_id][n_type] = {}
>                 notifications[n_dev_id][n_type][n_id] = notification
>                 _LOGGER.debug(
>                     "%s: Updated %s notifications for %s devices at %s",
>                     hide_email(email),
>                     len(raw_notifications),
>                     len(notifications),
>                     dt.as_local(
>                         hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"][
>                             "process_timestamp"
>                         ]
>                     ),
>                 )
>             else:
>                 _LOGGER.debug(
>                     "%s: No notifications were retrieved at %s",
>                     hide_email(email),
>                     dt.as_local(
>                         hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"][
>                             "process_timestamp"
>                         ]
>                     ),
>                 )
>         hass.data[DATA_ALEXAMEDIA]["accounts"][email]["notifications"] = notifications
> ```

Manually updating my files using the above seems to have worked for me too. My sensors are back and working thankfully. Honestly have zero idea what I did but needed the sensors working so gave it a go 😂

**Comment by NordFreak** [comment]
Interesting.

I wanted to install the fix, but apparently made a mistake somewhere, because after rebooting, AMP didn't work at all. Spook also reported missing entities. Since I forgot to make a backup of the init file, I downloaded it again via HACS 1.7.2 and restarted. After restarting, I was offered 1.7.3, so I installed the update and restarted again.

Interestingly, the error no longer appears in the log, and everything that worked before is now working again.

**Comment by wall83** [comment]
I have the same problem with the temperature sensor of my Alexa Echo Dot as well as with all the Air Quality sensors. The problem started  at 01:13:52 AM on November 17th I was using version 5.7.11 beta now I updated to 5.7.13 but the problem remained

<img width="1550" height="788" alt="Image" src="https://github.com/user-attachments/assets/ef4458ca-0957-4f0b-8a4f-f0bb8b8588a0" />

**Comment by omlnaut** [comment]
> I have the same problem with the temperature sensor of my Alexa Echo Dot as well as with all the Air Quality sensors. The problem started at 01:13:52 AM on November 17th I was using version 5.7.11 beta now I updated to 5.7.13 but the problem remained
> 
> <img alt="Image" width="1550" height="788" src="https://private-user-images.githubusercontent.com/3763908/516148930-ef4458ca-0957-4f0b-8a4f-f0bb8b8588a0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM1NDE1MDYsIm5iZiI6MTc2MzU0MTIwNiwicGF0aCI6Ii8zNzYzOTA4LzUxNjE0ODkzMC1lZjQ0NThjYS0wOTU3LTRmMGItOGE0Zi1mMGJiOGI4NTg4YTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMTlUMDgzMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWY2ODNkOTZjZTE5N2E4YWZmYmI5NmIzYmIzMDk5Mzc4ZWFkYWRkZTI1MzYyNmE4YzQ5OWE4OTY1NDJiOThhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JgWpTID0NjvvLhKaXAaKaQiL3aYTOglgKrLCEzGjWlw">

The pr linked above should fix the issue

**Comment by danielbrunt57** [comment]
> > "%s: Updated %s notifications for %s devices at %s",
> 
> I changed the code on in custom_components/alexa_media_player/**init**.py and reloaded the component. My changes don't seem to be active though. I added bunch of log statements to see where the error occurs, but I get none of those in the debug log. I changed the file with the File Editor plugin and saved, then reloaded the AMP extension. Is there something else I have to do so that changes to those local files are picked up?
> 
> Edit: Rebooting HA seems to do the trick. So far the suggested code change seems to work the temperature sensors have not gone unavailable for over an hour. I'll try creating a PR this evening, though can't promise I'll find the time.

Late reply but...
Reloading the component doesn't instantiate new code changes on disk into memory within the running container.  Those code changes only exist on disk and are only read once when HA first starts.

**Comment by danielbrunt57** [comment]
@omlnaut Is this still an issue in Release 5.8.0?

**Comment by omlnaut** [comment]
> [@omlnaut](https://github.com/omlnaut) Is this still an issue in Release 5.8.0?

I can't test this right now, I'm still running on 5.7.13 with the hot fix. 

I'll test this evening.

**Comment by danielbrunt57** [comment]
> I can't trust this right now, I'm still running on 5.7.13 with the hot fix.
> 
> I'll test this evening.

Totally understand that it's early still and you need time to test!

**Comment by omlnaut** [comment]
> > I can't trust this right now, I'm still running on 5.7.13 with the hot fix.
> > I'll test this evening.
> 
> Totally understand that it's early still and you need time to test!

I meant to say "test", not "trust" 😂

**Comment by R1200G** [comment]
It fixes it! 
Did the Update at 07:40. Since then everything works! 

Thanks! 👍🏼

![Image](https://github.com/user-attachments/assets/f8c79786-235b-43dc-bcb8-67360cd82311)

**Comment by omlnaut** [comment]
Issue is resolved with 5.8.0.

**Comment by fcrozat** [comment]
I still have the issue with 5.8.0, but I also have the alexa integration setup, it might cause too much queries

**Comment by danielbrunt57** [comment]
> I still have the issue with 5.8.0, but I also have the alexa integration setup, it might cause too much queries

Yes it might be.
There are more changes on the way though: New `alexapy` merge requests as well as `alexa_media` pull requests...
